# a cluster with 2 control-plane nodes and 2 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            enable-admission-plugins: "NodeRestriction,OwnerReferencesPermissionEnforcement"
  - role: control-plane
    kubeadmConfigPatches:
      - |
        apiVersion: kubeadm.k8s.io/v1beta2
        kind: ClusterConfiguration
        metadata:
          name: config
        apiServer:
          extraArgs:
            enable-admission-plugins: "NodeRestriction,OwnerReferencesPermissionEnforcement"
  - role: worker
  - role: worker